#!/bin/bash
set -e
pushd ~/dotfiles
sudo nixos-rebuild switch --flake ~/dotfiles &> nixos-switch.log || (cat nixos-switch.log) | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
